In [1]:
import numpy as np
import tensorflow as tf

import tensorflow_datasets as tfds

In [2]:
data, info = tfds.load('fashion_mnist', with_info=True, as_supervised=True)

In [3]:
train_data = data['train']
test_data = data['test']

In [4]:
for image, label in train_data.take(1):
    print(image)
    print(label)

tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 55]
  [ 92]
  [ 69]
  [ 74]
  [ 74]
  [ 7

In [5]:
def preprocess_data(images, labels):
    images = tf.cast(images, tf.float32)
    images = images / 255
    return images, labels

train_data = train_data.map(preprocess_data).batch(32)
test_data = test_data.map(preprocess_data).batch(32)

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2), 
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')     
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 1600)              0         
                                                                 
 dense (Dense)               (None, 32)                5

In [7]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
history = model.fit(train_data, validation_data=test_data, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 48s 25ms/step - loss: 0.5019 - accuracy: 0.8172 - val_loss: 0.3735 - val_accuracy: 0.8679
Epoch 2/10
1875/1875 [==============================] - 48s 26ms/step - loss: 0.3332 - accuracy: 0.8783 - val_loss: 0.3329 - val_accuracy: 0.8805
Epoch 3/10
1875/1875 [==============================] - 42s 22ms/step - loss: 0.2894 - accuracy: 0.8949 - val_loss: 0.3092 - val_accuracy: 0.8866
Epoch 4/10
1875/1875 [==============================] - 43s 23ms/step - loss: 0.2601 - accuracy: 0.9058 - val_loss: 0.2908 - val_accuracy: 0.8948
Epoch 5/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.2360 - accuracy: 0.9129 - val_loss: 0.2755 - val_accuracy: 0.8993
Epoch 6/10
1875/1875 [==============================] - 57s 31ms/step - loss: 0.2162 - accuracy: 0.9210 - val_loss: 0.2666 - val_accuracy: 0.9045
Epoch 7/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.1986 - accuracy: 0.9269 - val_loss: 0.2716 -

In [9]:
model.save('fashion_mnist.h5')